FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Run Angular dev server with live reload
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "3000", "--poll", "2000"]
