name: backend-ci
on: [push, pull_request]
permissions: { contents: read, packages: write }
jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }
      - run: dotnet restore Api/Api.csproj
      - run: dotnet build Api/Api.csproj --no-restore -c Release
      - run: echo "No unit tests yet"
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/backend:sha-${{ github.sha }},ghcr.io/${{ github.repository_owner }}/backend:latest
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/backend:sha-${{ github.sha }}
          format: table
          exit-code: '0'
