name: frontend-ci
on: [push, pull_request]
permissions: { contents: read, packages: write }
jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci || npm install
      - run: npm run lint || echo "No ESLint config yet"
      - run: npm test -- --runInBand
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/frontend:sha-${{ github.sha }},ghcr.io/${{ github.repository_owner }}/frontend:latest
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/frontend:sha-${{ github.sha }}
          format: table
          exit-code: '0'
